SpaceApps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('space_debris/', include('SpaceDebris.urls')),
    path('admin/', admin.site.urls),
]

SpaceDebris/urls.py
from django.urls import path

from . import views

app_name='SpaceDebris'

urlpatterns = [
    path('', views.index, name='index'),
    path('satellite/<str:satellite>/', views.info, name="info")
]

SpaceDebris/models.py
from django.db import models

# Create your models here.

SpaceDebris/views.py
from django.shortcuts import render
from sgp4.api import Satrec, SGP4_ERRORS 
from astropy.coordinates import TEME, CartesianDifferential, CartesianRepresentation, ITRS
from astropy import units as u
from astropy.time import Time

def index(request):    
    with open('SpaceDebris/active.txt') as f:
        lines = [line.rstrip() for line in f]
    names=[]
    for i in range(0, len(lines),3):
        names.append(lines[i])
    names=sorted(names)
    return render(request,"SpaceDebris/index.html",{
        'names':names
        })

def info(request,satellite):
    with open('SpaceDebris/active.txt') as f:
        lines = [line.rstrip() for line in f]
    index=lines.index(satellite)
    sat=lines[index]
    s=lines[index+1]
    t=lines[index+2]
    satellite = Satrec.twoline2rv(s,t)
    jd, fr = 2458827, 0.362605
    e, r, v = satellite.sgp4(jd, fr)
    if e != 0:
        raise RuntimeError(SGP4_ERRORS[e])
    teme_p = CartesianRepresentation(r*u.km)
    teme_v = CartesianDifferential(v*u.km/u.s)
    time = Time(jd, format='jd')
    teme = TEME(teme_p.with_differentials(teme_v), obstime=time)
    itrs = teme.transform_to(ITRS(obstime=time))  
    location = itrs.earth_location
    lon = location.geodetic[0].degree
    lat = location.geodetic[1].degree
    km = location.geodetic[2]
    return render(request,"SpaceDebris/info.html",{
        'sat':sat,
        's':s,
        't':t,
        'lon':lon,
        'lat': lat,
        'km': km,
    })

SpaceDebris/templates/SpaceDebris/index.html
{% extends "SpaceDebris/layout.html" %}

{% load static %}

{% block head %}
    <script type="text/javascript" src="{% static 'SpaceDebris/js/index.js' %}"></script>
{% endblock %}

{% block body %}
    <div id="data"></div>
    <div id="satellites">
        <h2>Satellites</h2>
        <ul>
            {% for name in names %}
            <li data-satellite="{{name}}"><button>{{name}}</button></li>
            {% endfor %}
        </ul>
    </div>
    
{% endblock %}

SpaceDebris/templates/SpaceDebris/info.html
{% extends "SpaceDebris/layout.html" %}

{% load static %}

{% block head %}
    <script type="text/javascript" src="{% static 'SpaceDebris/js/info.js' %}"></script>
{% endblock %}

{% block body %}
    <h1>Satellite - {{sat}}</h1>
    
    <h2>Orbital parameters in two-line element set (TLE) format</h2>
    <p>{{s}}</p>
    <p>{{t}}</p>
    <h2>Coordinates</h2>
    <ul>
        <li>Longitude: {{lon}}º</li>
        <li>Latitude: {{lat}}º</li>
        <li>Height: {{km}} </li>
    </ul>
{% endblock %}

SpaceDebris/templates/SpaceDebris/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Space Apps</title>
    <style>
        #canvasOne{
            background-color: black;
        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <h1><a href="{% url 'SpaceDebris:index' %}">Space Debris</a></h1>
    <canvas id="canvasOne" width="1024" height="768">
        Your browser does not support HTML5 Canvas.
    </canvas>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
    <script src="https://files.worldwind.arc.nasa.gov/artifactory/web/0.9.0/worldwind.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'SpaceDebris/js/layout.js' %}"></script>
    {% block body %}
    {% endblock %}
</body>
</html>